#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:

    - step:
        name: Checkout code
        script:
          - git clone https://bitbucket.org/sonikaj/fsm-network-visits.git

    - step:
        name: Pre-deploy steps
        script:
          - rm /bin/sh && ln -s /bin/bash /bin/sh && apt-get update && apt-get install -y git
          - python3 -m venv .venv
          - source .venv/bin/activate
          - pip install --upgrade pip
          - export PYTHONPATH="${PYTHONPATH}:."

    - step:
        name: Install dependencies
        script:
          - bash install_requirements.sh

    - step:
        name: Run static code checks
        script:
          - bash run_linters.sh
          
    - step:
        name: Run Pytests
        script:
          - bash install_requirements.sh
          - pip install pytest
          - pytest cloud_functions/tests/
          
    - step:
        name: Tests coverage
        script:
          - bash install_requirements.sh
          - bash coverage.sh

    - step:
        name: Deploy with Terraform
        # Requires Terraform CLI pre-installed
        script:
          - echo $SA_AUTH > /tmp/sa-auth.json
          - chmod 777 /tmp/sa-auth.json
          - gcloud auth activate-service-account $SA_NAME --key-file=/tmp/sa-auth.json --project="fsm-network"
          - gcloud config set project "fsm-network"
          - bash deploy.sh

#variables:
#  BITBUCKET_BUILD_NUMBER: $BITBUCKET_BUILD_NUMBER  # Replace with your variable name for build number (optional)
